"""website.

Revision ID: 6a2345cee9cb
Revises: ea51dc721fde
Create Date: 2022-08-19 17:47:07.260112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2345cee9cb'
down_revision = 'ea51dc721fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=500), nullable=False))
    op.drop_column('artists', 'website_link')
    op.add_column('venues', sa.Column('website', sa.String(length=500), nullable=False))
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('venues', 'website')
    op.add_column('artists', sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
